### ISSUE TITLE
temps d'execution, sauvegarde en cours

### ISSUE THREAD

**Issue by EricLF** [SocialGouv/archifiltre-docs#1206]
bonjour,
je fais tourner archifiltre sur un serveur virtuel.
il doit scanner un dossier de 405Go contenant 500 000 fichiers et 100 000 dossiers environ.

cela fait maintenant 3jours qu'il tourne en affichant cranement 500 000 fichiers indexés, C'est bientot fini...
1. comment estimer le temps que sera necessaire
2. si je redemarre le serveur ai-je moyen de lui faire reprendre la ou il c'est arreté ? (pour l'instant il recommence a 0)

désolé de passer par les Issues mais les messages dans discussions ne semblent pas etre lus ;-)

Merci pour l'appli en tout cas

**Comment by Alezco** [comment]
Bonjour,

Tout d'abord, désolé pour le temps de réponse dans la section "Discussions". Nous serons plus vigilants à l'avenir. Pour vous répondre : 
1. Nous avons déjà réfléchi à des solutions pour estimer le temps nécessaire à un import mais il y a trop d'incertitudes pour faire une bonne estimation : temps d'indexation des fichiers, matériel de la machine (SSD ou disque dur), fluctuations réseau en cas de lecture à distance, etc
2. Malheureusement, il n'y a pas d'option pour reprendre un chargement là où il s'était arrêté. Cependant, une fois l'import effectué, il est possible d'exporter son travail (donc l'ensemble de l'import et les enrichissements ajoutés) dans un fichier JSON (ré-importable dans Archifiltre) en utilisant le bouton "Enregistrer"

**Comment by bch4469** [comment]
Bonjour,

Je rebondis sur ce sujet de temps d'exécution.
Concernant le chargement des empreintes des fichiers et dossiers. Celui semble s'interrompre quand l'ordinateur bascule en veille ou quand la session se verrouille automatiquement après un temps d'inutilisation de l'ordinateur. 
Comment faire pour que Archifiltre tourne en arrière-plan toute une nuit par exemple ?

Cordialement,

**Comment by Alezco** [comment]
Bonjour,

Il n'y a pour le moment aucun mécanisme dans Archifiltre qui prévoit la gestion du mode veille. Mais l'idée est intéressante et nous allons l'étudier pour les prochaines versions. 

Merci pour l'idée !

**Comment by EricLF** [comment]
une semaine que ça tourne sur le serveur décrit dans mon premier message et pas d'avancées

normal ? ou j'annule a votre avis ?

**Comment by Alezco** [comment]
Bonjour,

S'il n'y a rien de nouveau après une semaine, c'est probablement qu'une erreur s'est produite et vous pouvez annuler le chargement

**Comment by EricLF** [comment]
Merci pour la réponse,
je vais passer par le script mais j'ai les erreurs suivantes:

je lance sur le script sur un serveur windows 2016 ds une fenetre powershell en administrateur et ou H:\public correspond au dossier a analyser et c:\temp le dossier ou je veux recuperer l'export

 .\load-from-filesystem.ps1 -Path H:\public > C:\temp


`Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:159 : 126
+ ... etails px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap" role="banner" >
+                                                                          ~
Spécification de fichier manquante après l’opérateur de redirection.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:390 : 21
+         <svg class="octicon octicon-sign-out v-align-middle" viewBox= ...
+                     ~~~~~~~
Jeton inattendu « octicon » dans l’expression ou l’instruction.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:471 : 67
+ ... mg src="https://avatars.githubusercontent.com/u/6400565?s=60&amp;v=4" ...
+                                                                 ~
Le caractère perluète n’est pas autorisé. L’opérateur & est réservé à une utilisation future. Placez un caractère
perluète entre guillemets doubles ("&") pour que ce symbole soit considéré comme une chaîne.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:473 : 18
+     <span class="dropdown-caret"></span>
+                  ~~~~~~~~~~~~~~~~~~~~~~~
Jeton inattendu « dropdown-caret"></span>
  </summary>
  <details-menu class="dropdown-menu » dans l’expression ou l’instruction.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:479 : 61
+           <svg style="box-sizing: content-box; color: var(--color-ico ...
+                                                             ~
Expression manquante après l’opérateur unaire « -- ».
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:479 : 61
+ ... yle="box-sizing: content-box; color: var(--color-icon-primary);" view ...
+                                                ~~~~~~~~~~~~~~~~~~
Jeton inattendu « color-icon-primary » dans l’expression ou l’instruction.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:479 : 61
+           <svg style="box-sizing: content-box; color: var(--color-ico ...
+                                                             ~
Parenthèse fermante « ) » manquante dans l’expression.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:479 : 79
+ ... le="box-sizing: content-box; color: var(--color-icon-primary);" viewB ...
+                                                                 ~
Jeton inattendu « ) » dans l’expression ou l’instruction.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:479 : 92
+ ... g: content-box; color: var(--color-icon-primary);" viewBox="0 0 16 16 ...
+                                                                 ~
Jeton inattendu « 0 » dans l’expression ou l’instruction.
Au caractère C:\Users\Administrateur.entreprise\Documents\load-from-filesystem.ps1:479 : 94
+ ...  content-box; color: var(--color-icon-primary);" viewBox="0 0 16 16"  ...
+                                                                 ~
Jeton inattendu « 0 » dans l’expression ou l’instruction.
Les erreurs d’analyse n’ont pas toutes été signalées. Corrigez les erreurs signalées, puis recommencez.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFileSpecification`

**Comment by EricLF** [comment]
bonjour,

Même erreur, j'ai essayé sur un autre poste cette fois en windows 10, pareil, meme erreur !

**Comment by cberthou** [comment]
Bonjour @EricLF ,
Ces erreurs laissent supposer que le fichier téléchargé n'est pas le bon. Voyez-vous le fichier .ps1 apparaître en cliquant sur ce lien ? (https://raw.githubusercontent.com/SocialGouv/archifiltre/master/scripts/load-from-filesystem.ps1)

Normalement, le fichier fait 665 octets.

**Comment by sam-pires** [comment]
Bonjour,

Avez-vous toujours l'erreur sur le script ?

Concernant la perfomance et le temps d'analyse nous allons nous y pencher en deuxième partie d'année
