### ISSUE TITLE
Generation du plan de classement 

### ISSUE THREAD

**Issue by MichelLux** [SocialGouv/archifiltre-docs#1248]
Bonjour
L'onglET du plan de classement dans les rapport ne peut être gégéra qu'avec l'option 'hash". Or celle-ci augmente trop le temps d'accès. Serait-il possible de désactiver le Hashage ?

**Comment by Alezco** [comment]
Bonjour @MichelLux. Pour générer un plan de classement, il est possible d'exporter un "CSV hiérarchisé" dans la fenêtre d'export. Cette option ne nécessite pas de calcul d'empreintes. Pour faire un export Excel sans empreintes, nous allons 
étudier l'idée pour peut-être l'ajouter à la prochaine version. Merci pour la suggestion.
