### ISSUE TITLE
Importer ses tags dans la bibliothèque

### ISSUE THREAD

**Issue by MacGraveur** [SocialGouv/archifiltre-docs#1278]
Comme pour le tag "à éliminer" il serait intéressant de pouvoir importer par défaut quelques autres termes. Ceci permettrait à l'archiviste/administrateur d'aiguiller les services dans leur choix de tag.

**Comment by sam-pires** [comment]
Bonjour @MacGraveur 
Merci pour le retour. Très bonne idée, vous êtes plusieurs en avoir fait part.
Je l'ai rajouté à la liste des suggestions pour que d'autres utilisateurs puissent la voir plus facilement et voter/commenter 
https://archifiltre.featurebase.app/p/avoir-une-liste-de-tags-personnalises-en-memoire

Je vous recommande de voter pour aussi, ça nous permettra de vous notifier dès que nous travaillerons sur le sujet
