### ISSUE TITLE
Redondances erronée

### ISSUE THREAD

**Issue by leguillou** [SocialGouv/archifiltre-docs#1373]
En scannant un répertoire comportant essentiellement des photos, je constate que l'outil trouve des redondances entre certaines qui n'ont pourtant aucun rapport.

Je ne sais pas très bien comment vous rendre le bug plus explicite mais si vous me dites ce dont vous avez besoin, je vous le fournirai avec plaisir.

**Comment by Alezco** [comment]
Bonjour @leguillou et merci pour ce signalement. 

Pouvez-vous nous envoyer deux fichiers différents qui sont détectés comme identiques par Archifiltre ? Vous pouvez par exemple les envoyer ici ou à archifiltre@sg.social.gouv.fr

Merci d'avance

**Comment by sam-pires** [comment]
Je ferme l'issue car une autre issue documente déjà ce bug
Merci
