### ISSUE TITLE
Chargement d'arborescence bloqué à 80/90%

### ISSUE THREAD

**Issue by sviscapi** [SocialGouv/archifiltre-docs#1376]
Bonjour,

Des collègues du Conseil Départemental de l'Hérault m'ont rapporté des problèmes avec Archifiltre, notamment des blocages à 80/90% lors de chargement d'arborescence.

Je me renseigne pour en apprendre un peu plus sur les environnements où ce bug se manifeste (OS, version du logiciel, etc...) pour vous faire un rapport un peu plus détaillé.

Cordialement,

Samuel, pour le Conseil Départemental de l'Hérault
https://herault.fr/

**Comment by Alezco** [comment]
Bonjour @sviscapi et merci pour ce signalement. Nous travaillons sur ce problème (coriace) qui sera corrigé dans la prochaine version d'Archifiltre. Merci pour votre patience :)

**Comment by sviscapi** [comment]
Bonjour @Alezco et merci pour votre retour rapide. Si vous avez besoin de beta-testeurs, vous savez où me trouver ;) Cordialement, Samuel

**Comment by Alezco** [comment]
Bonjour @sviscapi ! Le problème a peut-être été résolu par la nouvelle version d'Archifiltre téléchargeable ici : https://archifiltre.fr/telechargements

Attention : Archifiltre devient Archifiltre-Docs, et la version proposée est une beta, qui contient peut-être des bugs. Si vous souhaitez la tester, nous sommes preneurs de vos retours :)
