### ISSUE TITLE
Problème de chargement de répertoire photos

### ISSUE THREAD

**Issue by Lauriane1997** [SocialGouv/archifiltre-docs#1388]
Bonjour, 

Je dois traiter un répertoire contenant en grande majorité des photos. J'aimerais établir un rapport d'audit pour sensibiliser les producteurs avec l'application mais lorsque j'ajoute le répertoire le calcul des hash reste à 0% et n'avance pas. J'ai fait 3 tests avec le même résultat. Y a-t-il une solution à ce problème ? 

Merci d'avance pour votre aide, 
Bien cordialement,
Lauriane

**Comment by Alezco** [comment]
Bonjour @Lauriane1997 et merci pour ce retour. Nous sommes conscients de ce bug et nous travaillons dessus pour le corriger dans la prochaine version d'Archifiltre. Merci pour votre patience :)

**Comment by Lauriane1997** [comment]
Bonjour @Alezco, merci pour votre retour ! On patiente alors :) Avez-vous une idée de la date de sortie de la prochaine version ?

**Comment by Alezco** [comment]
Nous sommes en phase de transition et beaucoup de nouveautés vont arriver dans Archifiltre, mais je ne peux pas avancer de date pour le moment. Dès que la nouvelle version sortira, une communication sera faite ici et sur les réseaux sociaux. Une fois de plus, merci pour votre patience :)

**Comment by Alezco** [comment]
Bonjour @Lauriane1997 ! Le problème a été résolu par la nouvelle version d'Archifiltre téléchargeable ici : https://archifiltre.fr/telechargements

Attention : Archifiltre devient Archifiltre-Docs, et la version proposée est une beta, qui contient peut-être des bugs. Si vous souhaitez la tester, nous sommes preneurs de vos retours :)
