### ISSUE TITLE
Corriger pop-up sur la détection des fichiers ZIP

### ISSUE THREAD

**Issue by Thibaut-Larrede** [SocialGouv/archifiltre-docs#1396]
**EPIC**

**AFTER**

**Contexte**
Lorsqu'on charge un répertoire dans Archifiltre-Docs, une pop-up s'ouvre pour indiquer qu'il y a des fichiers ZIP et qu'ils ne sont pas pris en charge.

**Définition du(des) problème(s)**
La pop-up n'est plus compréhensible. Il faut remplacer "productNameShort" par Archifiltre Ou Archifiltre-Docs ou Docs

![image](https://user-images.githubusercontent.com/60773821/153932595-f008c3ed-a84a-4aab-b8e9-6d486e9ddf3e.png)

**Solution**
ETQ utilisateur d'Archifiltre-Docs
JVP avoir la pop-up avec le nom du produit
AD de comprendre facilement la pop-up

**Critères d'acceptance**
No response

**Les tests e2e doivent-ils passer ?**
e2e

**Valeur Business**
BV:S

**Comment by lsagetlethias** [comment]
Caused by #1389
