### ISSUE TITLE
Recherche sur le critère "À éliminer"

### ISSUE THREAD

**Issue by El-Gavy** [SocialGouv/archifiltre-docs#1403]
Via l’onglet "Enrichissement" j’ai ajouté le tag "À éliminer" sur de nombreux éléments.

Dans l’écran de recherche il me semblerait utile de pouvoir facilement afficher les fichiers et répertoire ayant ce tag, cependant ne sont proposés que les tags que j’ai créés : 

![image](https://user-images.githubusercontent.com/26960332/155540668-5dd0df79-fd63-47cf-bcfc-2b84b128bd98.png)

**Comment by Alezco** [comment]
Bonjour @El-Gavy et merci pour ce retour. Nous avons identifié cette fonctionnalité et elle sera peut-être priorisée dans notre travail à l'avenir

**Comment by sam-pires** [comment]
Bonjour @El-Gavy 
Cette amélioration a été apportée à Docs. 
Si ce n'est pas déjà fait je vous invite à télécharger la dernière version
https://archifiltre.fr/telechargements

Merci,
