### ISSUE TITLE
Fonctionnalités sur les tags dans l’écran de recherche et édition en lots

### ISSUE THREAD

**Issue by El-Gavy** [SocialGouv/archifiltre-docs#1404]
Dans l’écran de recherche il est seulement possible d’activer "À éliminer" pour les fichiers et répertoires trouvés.

Il serait appréciable de voir directement dans les résultats les tags affectés aux éléments et pouvoir les modifier, notamment en lots.

**Comment by Alezco** [comment]
Bonjour @El-Gavy. Nous n'avons pas pensé à cette idée mais nous l'ajoutons à notre liste de fonctionnalités à réfléchir. Merci pour la suggestion.

**Comment by sam-pires** [comment]
Bonjour @El-Gavy 
Je ferme l'issue mais nous avons bien noté votre suggestion
