### ISSUE TITLE
Pouvoir chercher sur des tailles de fichiers personnalisées

### ISSUE THREAD

**Issue by El-Gavy** [SocialGouv/archifiltre-docs#1405]
Il est très pratique de pouvoir chercher par rapport à la taille de fichiers mais les 4 options proposées sont trop restrictives, dans l’idéal il faudrait en plus pouvoir définir soi-même les valeurs. Par exemple si je veux retrouver tous les fichiers qui font plus de 50 Mo et moins de 500 Mo.

![image](https://user-images.githubusercontent.com/26960332/155544015-9058c105-6b20-4a5c-a00d-72b7dfbd64d0.png)

**Comment by Alezco** [comment]
Bonjour @El-Gavy. De la même manière que les autres suggestions, nous l'ajoutons à notre liste, merci pour la proposition

**Comment by Alezco** [comment]
Bonjour @El-Gavy. De la même manière que les autres suggestions, nous l'ajoutons à notre liste, merci pour la proposition

**Comment by sam-pires** [comment]
Bonjour @El-Gavy 
Votre retour est similaire à une idée déjà remontée et partagée sur Featurebase.
Je vous invite à la voir et la compléter. Il ne s'agit pas exactement de la même idée mais le besoin est très proche. La variété de façon de faire proposée sera intéressante pour que nous fassions le choix le plus juste 
https://archifiltre.featurebase.app/p/filtrer-larborescence-pour-ne-voir-que-certains-types-de-fichier

Merci
