### ISSUE TITLE
Arborescence tronquée si trop importante

### ISSUE THREAD

**Issue by El-Gavy** [SocialGouv/archifiltre-docs#1406]
**Describe the bug**
Si l’arborescence d’un élément est trop importante, elle ne s’affiche pas correctement dans la colonne de droite de la visualisation (le bas de l’arborescence est masquée derrière la "mini carte".

**To Reproduce**
1. Sélectionner un élément ayant une arborescence importante : 

![image](https://user-images.githubusercontent.com/26960332/155545775-dadf3095-e677-43e7-8980-cf51c063fe7b.png)

**Expected behavior**
L’affichage devrait se compacter pour tout afficher au-dessus de la mini carte ou alors il devrait y avoir un ascenseur vertical.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Version :  Archifiltre 3.2.2]

**Comment by Alezco** [comment]
Bonjour @El-Gavy et merci pour cette remontée de bug. Il a été identifié et corrigé. Cette correction sera disponible dans la prochaine version d'Archifiltre

Enfin, si vous souhaitez faire une interview utilisateur pour proposer des idées ou remonter des bugs, vous pouvez envoyer un mail à [archifiltre@sg.social.gouv.fr](mailto:archifiltre@sg.social.gouv.fr).

Bonne journée

**Comment by El-Gavy** [comment]
Bonjour,

J’ai téléchargé et testé la version [v3.3.0-next.6](https://github.com/SocialGouv/archifiltre-docs/releases/tag/v3.3.0-next.6) et effectivement je n’ai plus le souci.
