### ISSUE TITLE
Prise en compte des chemins trop longs et fichiers à renommer dans le rapport ?

### ISSUE THREAD

**Issue by sviscapi** [SocialGouv/archifiltre-docs#1410]
Bonjour,

Mes collègues archivistes souhaiteraient voir figurer le nombre de chemins trop longs ainsi que les fichiers nécessitant un renommage technique dans le rapport généré par Archifiltre.

Pensez-vous que cette fonctionnalité puisse être ajoutée au logiciel ?

Merci et bonne journée.

Cordialement,

Samuel, pour le Conseil Départemental de l'Hérault

**Comment by ChloeMoser** [comment]
Bonjour,
Merci beaucoup pour votre proposition et cette remontée qui rejoint des éléments signalés par d'autres utilisateurs (pour les chemins trop longs).
Je vous confirme que cette évolution est prévue dans les prochaines évolutions.

En revanche, en ce qui concerne les nécessités de renommage technique, serait-il possible d'avoir le détail de ce qui serait utile?

Bien cordialement,
Chloé Moser, product manager d'Archifiltre

**Comment by sviscapi** [comment]
Bonjour,

Veuillez m'excuser pour la réponse tardive.

En ce qui concerne le renommage technique, il s'agirait de repérer et d'alerter l'utilisateur en cas de fichiers comprenant des accents, des espaces, des caractères spéciaux, etc... Une liste en sortie avec tous les fichiers posant problème serait un plus.

D'autres fonctionnalités souhaitées par mes collègues archivistes (pour améliorer le dialogue avec les SP / SV):

* Faire évoluer le rapport d'audit (qui est déjà très bien) : ajouter un champ personnalisable pour description du corpus, nom du service versant, service producteur, date de l'analyse, identifiant éventuel pour l'analyse
* Enrichir les chiffres clés: plus gros dossier, nombre de fichiers maximum, nom de fichier le plus long (à faire figurer plus haut dans le rapport).
* Ajouter une alerte configurable sur la longueur maximale pour un nom de fichier
* Ajouter une alerte configurable quand une date n'est pas au format attendu (ex: AAAMMJJ)

Qu'en pensez-vous ?

Merci et bon après-midi.

Cordialement,

Samuel, pour le Conseil Départemental de l'Hérault

**Comment by CoralineRey** [comment]
Bonjour, 

Je me permets de rebondir, un peu tardivement car j'utilise Archifiltre depuis peu.
Les fonctionnalités demandées ci-dessus seraient effectivement très utiles pour sensibiliser les producteurs de documents.

Bien cordialement,

**Comment by Maudelaurence** [comment]
Bonjour, 
Je recherche également des noms trop longs. Cependant, lors du chargement du dossier, avant même le début du chargement des empruntes, j'ai un grand nombre d'erreurs. J'ai remarqué en étudiant les erreur que c'était justement mes fichiers trop longs qui bloquaient. Est-ce que c'est possible? La plupart du temps, je ne suis pas capable de charger les empruntes si mon dossier est volumineux, donc si je peux être sûr que mes erreurs sont les chemins d'accès de plus de 260 caractères, ça règle mon problème!
Merci beaucoup,

**Comment by CoralineRey** [comment]
Bonjour, 
J'ai mené des tests avec des dossiers à volumétrie différente, comportant des fichiers à noms trop longs et/ou des dossiers zips. Tests avec différentes versions d'Archifiltre.
Les empreintes se chargent toujours.
Ce sont les exports excel, csv qui fonctionnent ou pas, sans que je n'aie réussi à déterminer la cause des échecs (pas le volume, pas le nombre de fichiers, pas les noms trop longs, pas les zips).
Bonne journée,

**Comment by sam-pires** [comment]
Bonjour,
Merci pour ces retours.
Je viens de créer une carte sur notre nouvel outils de suggestions 
https://archifiltre.featurebase.app/p/configurer-des-alertes-sur-le-nommage-les-formats-etc
Je vous invite à y aller et voter et commenter (ça nous permettra aussi de vous tenir au courant quand nous travaillerons sur ce sujet)
