### ISSUE TITLE
Archifiltre doc sur Centos 7

### ISSUE THREAD

**Issue by georgkasten** [SocialGouv/archifiltre-docs#1428]
Bonjour,

je souhaite utiliser archifiltre doc sur mes serveurs de fichiers en Centos 7 mais j'ai le message d'erreur ci-dessous.

./archifiltre-3.2.2.AppImage
[0509/094454.471800:FATAL:electron_main_delegate.cc(297)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180. Trace/breakpoint trap

Il y aurait une solution pour les machines sous Debian mais visiblement elle n'est pas applicable pour Centos 7.
Auriez-vous une solution ?

**Comment by sam-pires** [comment]
Bonjour, 

Nous sommes en train de travailler sur un paquet Debian.
Je vous tiens informé quand il est prêt
