### ISSUE TITLE
Erreur lien de téléchargement 

### ISSUE THREAD

**Issue by AngeliqueCe** [SocialGouv/archifiltre-docs#1441]
Bonjour,

Les liens de téléchargement de la page https://archifiltre.fr/telechargements   :
https://github.com/SocialGouv/archifiltre-docs/releases/download/v4.0.0-next.3/archifiltre-docs-4.0.0-next.3.exe
https://github.com/SocialGouv/archifiltre-mails/releases/download/v1.0.0-next.7/archifiltre-mails-1.0.0-next.7.exe
ne fonctionnent pas. Le lien conduit à une page 404 not found. 

Merci !

**Comment by mehdilouraoui** [comment]
Bonjour @AngeliqueCe, merci pour votre rapport d'erreur. Nous avons bien corrigé les liens de téléchargements, vous pouvez de nouveau consulter l'URL suivante pour télécharger les dernières versions de Docs et Mails : [](https://archifiltre.fr/telechargements)

Cliquez sur `besoin d'une autre version` pour trouver les versions antérieures. 

Merci !
