### ISSUE TITLE
Problème d'export des fichiers de récolement

### ISSUE THREAD

**Issue by Shannesse** [SocialGouv/archifiltre-docs#1443]
**Describe the bug**
Bonjour, l'export des fichiers de récolement ne fonctionnent pas dès que le dossier analysé est trop volumineux. J'ai effectué plusieurs essais: un dossier de quelques Go, cela fonctionne mais dès que ça atteint plusieurs dizaines voire centaines de Go, seul le rapport d'audit est exporté même après attente du calcul des hash.

Le message en haut à droit indique que l'export a commencé mais il reste à 0%.

**Desktop (please complete the following information):**
 - Windows 10 Professionnel
 - Version [e.g. Docs par Archifiltre 4]

**Comment by ChloeMoser** [comment]
Dupliqué de #1442
