### ISSUE TITLE
Probleme chargement des empreintes 

### ISSUE THREAD

**Issue by pixelfondu** [SocialGouv/archifiltre-docs#1448]
Comme tout le monde je ne peux pas obtenir d'audits ni une visualisation des redondances... C'est dommage car c'est bien là un gros point fort d'Archifiltre. Ça fait quand même un bon moment que le problème persiste!

**Comment by Alexandre-De** [comment]
J'ai moi aussi ce problème :/ ...! Étrange, ça a fonctionné pour quelques répertoires, puis ça a cessé de fonctionner. Le calcul des empreintes reste à 0%, mais le serveur travaille (presque 100% du CPU affecté).
