### ISSUE TITLE
Problème d'export des CSV

### ISSUE THREAD

**Issue by Alexandre-De** [SocialGouv/archifiltre-docs#1461]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Il arrive fréquemment qu'Archifiltre version 4.0.0 beta 4 n'arrive pas à exporter le récolement en CSV. L'export commence, puis gèle à 0%, et rien ne se passe. Parfois, à force de répéter (fermer et redémarrer le logiciel), ça finit par fonctionner... mais pas toujours. Mon équipe éprouve ce problème depuis la semaine du 11 juillet 2022.

### Étapes pour reproduire

Charger un JSON, exporter en CSV. L'erreur étant intermittente, il est difficile de la répéter de manière infaillible.

### Comportement attendu

La production du rapport gèle à 0%.

### Liste des caractéristiques de votre machine

Windows 10, 64 bits, 4 Go Ram, processeur Intel i5

### Version de l'application

beta (à préciser dans les caratéristiques)

### Informations complémentaires

4.0.0 beta 4

**Comment by Alexandre-De** [comment]
AJOUT : je me rends compte que l'exportation fonctionne SI : 1) je ferme complètement Archifiltre après chaque JSON (et non simplement utiliser le petit bonhomme au haut à droite / Fermer) ; 2) si je choisis le même serveur comme endroit d'enregistrement du fichier d'export. Dès que j'essaie d'exporter sur un autre emplacement réseau ou sur mon OneDrive, ça ne fonctionne pas.

**Comment by lsagetlethias** [comment]
Bonjour ! Ce problème devrait être corrigé dans la version https://github.com/SocialGouv/archifiltre-docs/releases/tag/v4.0.0-beta.6 ; n'hésitez pas à nous indiquer que ça fonctionne pour vous aussi. 👌
