### ISSUE TITLE
La colonne "A éliminer" n'est plus présente dans les exports CSV/excel

### ISSUE THREAD

**Issue by cberthou** [SocialGouv/archifiltre-docs#1477]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

La colonne "A éliminer" n'est plus présente dans les exports CSV/excel

### Étapes pour reproduire

1. Charger une arborescence
2. Identifier des éléments "A éliminer"
3. Générer un export CSV 

### Comportement attendu

La colonne A éliminer est présente.

### Liste des caractéristiques de votre machine

- 4.0.0 beta 8

### Version de l'application

beta (à préciser dans les caratéristiques)

**Comment by sam-pires** [comment]
A priori la PR a fixé le bug
Je ferme l'issue
