### ISSUE TITLE
Impossible d'exporter le récolement CSV

### ISSUE THREAD

**Issue by PorfiP** [SocialGouv/archifiltre-docs#1486]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Bonjour,

Je suis nouveau dans cette communauté. J’utilise Archifiltre actuellement, mais j’éprouve de la difficulté à exporter le fichier en CSV avec la v4.0.0 (next. 10). En lisant les commentaires, j’ai cru comprendre que le problème de bogue pouvait être résolu avec cette version. De plus, mes collègues ont le même problème. Impossible d'exporter le CSV.

Avez-vous une piste de solution pour m’aider à avancer?
Merci de votre collaboration.

Porfirio
Techniciens en gestion de l’information (Documentation)

### Étapes pour reproduire

1. sur cet écran

### Comportement attendu

À la suite du lancement, une fenêtre apparaît indiquant que l’export CSV a commencé. 

Mais compter reste toujours à 0%. 

### Captures d'écran (si possible)

![image](https://user-images.githubusercontent.com/116571931/197548731-7e760cc9-1876-4596-8912-ce46629f5253.png)

![image](https://user-images.githubusercontent.com/116571931/197548821-a372c008-2556-4767-be2a-613de810c4a7.png)

### Liste des caractéristiques de votre machine

- OS Windows 10 
- Intel

### Version de l'application

next (à préciser dans les caratéristiques)

### Informations complémentaires

Salut! Afin d'avancé dans le travail à faire, j'ai déjà testé d'autres versions : v3.2.2, beta v4.0.0
Je n'ai pas eu des résultats. Le Bogue persiste.

**Comment by ChloeMoser** [comment]
Bonjour,
Merci beaucoup d'avoir rempli le ticket et nous avoir indiqué cette anomalie.
Nous sommes en train de travailler sur cette anomalie bloquante pour plusieurs utilisateurs et reviendrons vers vous dès que nous aurons une version corrective.

**Comment by sam-pires** [comment]
Bonjour @PorfiP 
Avez-vous toujours le problème ?

Je vous invite à télécharger la v4.1 au passage, tenez moi au courant si vous le problème sur cette version.
https://archifiltre.fr/telechargements

merci

**Comment by sam-pires** [comment]
Bonjour @PorfiP,
Nous avons enfin corrigé le bug lié à la génération d'export CSV avec Empreintes dans notre dernière version v.4.2
Je vous invite à la tester : https://archifiltre.fabrique.social.gouv.fr/telechargement

Si vous encore un problème vous pouvez nous contacter à cet adresse: archifiltre@fabrique.social.gouv.fr
