### ISSUE TITLE
Impossible d'exporter CVS ou Excel

### ISSUE THREAD

**Issue by smatrone** [SocialGouv/archifiltre-docs#1495]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Bonjour,
utilisant Archifiltre pour mes extractions/recolement, il m'est impossible aujourd'hui d'exporter un tableur hiérarchisé/empreintes. Le téléchargement se lance mais ne commence pas: il reste bloqué à 0%. J'ai cru voir ce problème apparaître fréquemment et cela m'empêche de travailler convenablement.  @cberthou

### Étapes pour reproduire

1. Lancement du repertoire/json
2. Attendre le chargement du fichier
3. Exporter
4. Choix de l'extension: récolement > cvs empreinte/hiérarchisé
5. Choix du chemin
6. Exporter

### Comportement attendu

Chargement de l'export

### Liste des caractéristiques de votre machine

- Windows 10

### Version de l'application

3.x

**Comment by sam-pires** [comment]
Bonjour @smatrone 

Avez-vous toujours le problème.
Je vous invite à télécharger notre dernière version v4.1
https://archifiltre.fr/telechargements

Tenez moi au courant si vous avez toujours le problème sur cette version
Merci,

**Comment by TimotheeMalard** [comment]
https://github.com/SocialGouv/archifiltre-docs/issues/1486
