### ISSUE TITLE
Anomalie Export "Resip" colonne "File"

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1505]
### Discussed in https://github.com/SocialGouv/archifiltre-docs/discussions/1503

<div type='discussions-op-text'>

<sup>Originally posted by **Loracahur** January 10, 2023</sup>
Bonjour,
L'export "Resip" comporte une erreur. La donnée de la colonne "File" concernant le "RecordGrp" est absente. De ce fait lors de la vérification de la conformité avec le SEDA le résultat est négatif. </div>

**Comment by sam-pires** [comment]
Bonjour @loracahur,

Concernant ce bug, quel serait le comportement attendu ?

J'ai testé sur la v4.1 et les éléments "RecordGrp" s'affiche dans la colonne DescriptionLevel (voir capture).
<img width="146" alt="Capture d’écran 2024-03-25 à 16 49 33" src="https://github.com/SocialGouv/archifiltre-docs/assets/25405887/2606cfcc-f458-4036-a49b-9bce4edf928b">


D'après ce que j'ai trouvé dans la [Doc Resip](https://www.programmevitam.fr/ressources/DocCourante/autres/fonctionnel/VITAM_Manuel_ReSIP.pdf), à la page 72, c'est bien le fonctionnement attendu.

Je suis preneur de tout retour.

**Comment by Loracahur** [comment]
Bonjour,

J’ai vérifié  le csv Resip en le confrontant au standard SEDA 2.1 et le test et positif. En conclusion la nouvelle version n’indique plus cette erreur.

Bien cordialement,

***@***.***

Carol RUHA
Assistant archiviste
Direction Relation à l'Usager et Services Internes
Ville de Cergy
Tél : 01 34 33 44 65
Hôtel de ville - 3, place Olympe de Gouges
BP 48 000 Cergy – 95 801 Cergy-Pontoise cedex
[logos sociaux]  villedecergy   [instagram]  JeunesACergy<http://www.instagram.com/jeunesacergy/> - www.cergy.fr<http://www.cergy.fr/>












De : Samuel Pirès ***@***.***>
Envoyé : lundi 25 mars 2024 16:56
À : SocialGouv/archifiltre-docs ***@***.***>
Cc : RUHA, Carol ***@***.***>; Mention ***@***.***>
Objet : Re: [SocialGouv/archifiltre-docs] Anomalie Export "Resip" colonne "File" (Issue #1505)


Bonjour @Loracahur<https://github.com/Loracahur>,

Concernant ce bug, quel serait le comportement attendu ?

J'ai testé sur la v4.1 et les éléments "RecordGrp" s'affiche dans la colonne DescriptionLevel (voir capture).
Capture.d.ecran.2024-03-25.a.16.49.33.png (view on web)<https://github.com/SocialGouv/archifiltre-docs/assets/25405887/2606cfcc-f458-4036-a49b-9bce4edf928b>

D'après ce que j'ai trouvé dans la Doc Resip<https://www.programmevitam.fr/ressources/DocCourante/autres/fonctionnel/VITAM_Manuel_ReSIP.pdf>, à la page 72, c'est bien le fonctionnement attendu.

Je suis preneur de tout retour.

**Comment by sam-pires** [comment]
Merci pour le retour @Loracahur 👍
