### ISSUE TITLE
BUG  ARCHIFILTRE CL/ Impossible d'exporter le fichier CSV avec empreintes

### ISSUE THREAD

**Issue by Genevieve-Kayossi** [SocialGouv/archifiltre-docs#1518]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

il nous est impossible aujourd'hui d'exporter un tableau hiérarchisé/empreintes. Le téléchargement se lance mais ne commence pas : il reste bloqué à 0 %. Ce problème dure depuis une semaine et cela nous empêche de travailler convenablement.
Nos dossiers sont volumineux mais nous faisons toujours en sorte de ne pas dépasser 10000 fichiers par traitement archifiltre. Il est possible d'exporter pour les VRACS avec trés peu de redondance (15) mais avec les VRACS  (600+) redondance le logiciel ne réponds plus.
Nous utilisons la derniere version celle que vous nous avez envoyez par mail mais cela ne fonction toujours pas.

### Étapes pour reproduire

Allez sur le logiciel
Exporter le fichier JSON 
Attendre le chargement d'empreintes 
Ensuite cliquer sur exporter et choisir le fichier CSV avec empreinte

### Comportement attendu

Fichier CSV télécharger

### Captures d'écran (si possible)

![image](https://user-images.githubusercontent.com/121496438/221632718-6e9f06ec-dd18-4934-b1f2-7383f7b48bd1.png)

### Liste des caractéristiques de votre machine

OS

### Version de l'application

4.x

### Informations complémentaires

Les dossiers sont dans le serveur partager de l'entreprise mais il y a que mon equipe qui en a acces.

**Comment by ChloeMoser** [comment]
Bonjour,
Merci beaucoup d'avoir rempli le ticket et nous avoir indiqué que l'anomalie se produit bien sur la dernière version disponible.
Nous sommes en train de travailler sur cette anomalie bloquante pour plusieurs utilisateurs et reviendrons vers vous dès que nous aurons une version corrective.

**Comment by Adelie-Talour** [comment]
Bonjour @ChloeMoser, nous serions intéressés de savoir si le problème évoqué par @Genevieve-Kayossi avait été résolu. Nous travaillons sur la dernière version v3.2.2 d'Archifiltre et aurions besoin de savoir si le blocage d'exports de taille importante (84 Go, soit près de 35 000 fichiers) était normal. J'entends par blocage le fait que passé plusieurs heures de chargement, le système continue de charger.

Merci par avance pour votre retour

**Comment by sam-pires** [comment]
Bonjour @Adelie-Talour @Genevieve-Kayossi 
Je vous invite à télécharger la dernière version, v4.1 et retester : https://archifiltre.fr/telechargements
Si le problème persiste, pouvez-vous me contacter par email, j'aurai besoin de voir avec vous comment reproduire de mon côté avec un dossier de test.

**Comment by sam-pires** [comment]
related to #1628

**Comment by sam-pires** [comment]
bug reproduit en v4.1.2

**Comment by Bernard-VAL** [comment]
Bonjour

J’ai également reproduit ce bug en v4.1.2 sur 2 arborescences

Merci


Bernard LEULLIETTE
Archiviste Numérique
Service Commun des Archives
03 27 09 60 65 / 06 49 31 34 16

***@***.******@***.***




De : Samuel Pirès ***@***.***>
Envoyé : mercredi 28 août 2024 16:46
À : SocialGouv/archifiltre-docs ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [SocialGouv/archifiltre-docs] BUG ARCHIFILTRE CL/ Impossible d'exporter le fichier CSV avec empreintes (Issue #1518)


bug reproduit en v4.1.2

**Comment by sam-pires** [comment]
Bonjour @Genevieve-Kayossi, @Adelie-Talour , @Bernard-VAL 
Nous avons résolu ce bug dans la version 4.2.0 qui vient de sortir !
Vous pouvez la télécharger sur notre site https://archifiltre.fabrique.social.gouv.fr/telechargement
