### ISSUE TITLE
archifiltre-docs-win-x64-portable.exe reste bloqué lors de la modification des paramètres de confidentialité

### ISSUE THREAD

**Issue by Chlara** [SocialGouv/archifiltre-docs#1531]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

J’ai fait un petit test avec la Pre-release « archifiltre-docs-win-x64-portable.exe » (4.0.0-next.11  de 2022-12-02). 
Je voulais changer les paramètres de confidentialité. Je peux par exemple changer « Données et statistiques d’utilisation » mais dé que je appuis sur « sauvegarder et recharger » archifiltre reste bloqué.
L'utilisateur doit fermer l'application et lorsqu'il la redémarre, les paramètres n'ont pas été modifiés.

### Étapes pour reproduire

1.	Cliquer sur le bouton « Paramètres » et « confidentialité » 
2.	Changer « Données et statistiques d’utilisation » 
3.	Cliquer sur le bouton « sauvegarder et recharger » 
4.	Constater l’erreur

### Comportement attendu

Archifiltre doit changer les paramètres de confidentialité et pas reste bloqué

### Captures d'écran (si possible)

![grafik](https://user-images.githubusercontent.com/1552939/231680375-946efc02-8ac1-4fe4-81e1-268542812188.png)

### Liste des caractéristiques de votre machine

-	Windows 11
-	archifiltre-docs-win-x64-portable.exe  (4.0.0-next.11  de 2022-12-02)

### Version de l'application

next (à préciser dans les caratéristiques)

**Comment by sam-pires** [comment]
à investiguer

**Comment by AnneLaureF** [comment]
Bonjour,

Je rencontre exactement le même bug sous Linux avec la version 4.0.0 stable.

Système (même comportement sur 2 ordinateurs différents):
- Debian 12.4
- Debian 11.4

Version de l'application:
4.0.0 stable: archifiltre-docs-linux-x86_64.AppImage

![image](https://github.com/SocialGouv/archifiltre-docs/assets/497836/bc58465c-7e6d-4e51-a90f-c8fdbcecbd83)

à noter qu'à la fermeture (même sans rien faire d'autre que démarrer l'application puis la fermer) j'obtiens dans mon terminal une erreur de segmentation.

**Comment by sam-pires** [comment]
Bonjour @Chlara @AnneLaureF 

Le problème a été résolu dans la dernière version d'Archifiltre, v4.1
Je vous invite à la télécharger https://archifiltre.fr/telechargements
