### ISSUE TITLE
Blocage lors du chargement d'un fichier json/txt

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1566]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Lors du dépôt d'un fichier .txt généré par le script passé par la DNUM, l'affichage de l'arborescence se fait pendant 1 seconde puis l'écran devient blanc complètement. Il est alors impossible de faire la moindre action à part fermer la fenêtre mais impossible d'analyser l'arborescence, l'enrichir, éditer les exports.
Pour précision, les ressources de l'ordinateur utilisé ne sont pas du tout mobilisées par Archifiltre au moment où l'écran devient blanc.
Autre précision: l'anomalie est irrégulière sur le même poste.

### Étapes pour reproduire

- Sur la page de lancement, charger un fichier json, txt ou une arborescence volumineuse (+ de 400 Go ou 1 000 000 fichiers)
- Laisser charger l'arborescence
- L'affichage de l'arborescence se fait 

### Comportement attendu

L'arborescence doit rester affichée après le chargement et ne pas se bloquer

### Captures d'écran (si possible)

![MicrosoftTeams-image](https://github.com/SocialGouv/archifiltre-docs/assets/62606616/2e9d12ec-39ba-4dd6-b40c-624e39d732f0)

### Liste des caractéristiques de votre machine

- OS Windows 10 Professionnel 22H2
- 16 Go de RAM (15,é utilisable)
- Processeur: AMD Ryzen 5 PRO 4650U with Radeon Graphics   2.10 GHz
- Version utilisée: v4.0.0-next.14

### Version de l'application

next (à préciser dans les caratéristiques)

**Comment by sam-pires** [comment]
Bonjour,

Le bug d'écran blanc été corrigé dans notre dernière release v.4.1.2 🛠️
Vous pouvez la télécharger sur notre [site](https://archifiltre.fr/) ou directement sur [Github](https://github.com/SocialGouv/archifiltre-docs/releases) si vous cherchez une version spécifique.


Merci pour votre aide 😃
