### ISSUE TITLE
Problème d'export Excel à sur Archifiltre 3.2.2

### ISSUE THREAD

**Issue by sam-pires** [SocialGouv/archifiltre-docs#1571]
Bonjour,

Config
Win 10 pro, proc Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz 2.11 GHz , ram 8Go, dossier de 9Go 14000 fichiers, archifiltre 3.2.2 (stable).
L'export Excel démarre puis reste à zéro. J'ai observé dans le gestionnaire de performance win. une crête maximale de l'utilisation mémoire lors du démarrage de l'export puis la crète descend est reste stable mais archifiltre semble ne plus être actif. J'ai fait le teste avec la même config mais avec archifiltre 3.1.1. L'export se déroule bien et je n'ai pas observé la crête de consumation maximale de mémoire. Question : La configuration matériel présentée ci-dessous est-elle suffisante (mémoire) ?

_Originally posted by @Loracahur in https://github.com/SocialGouv/archifiltre-docs/discussions/1438#discussioncomment-2903703_

**Comment by sam-pires** [comment]
Problème mentionné dans une autre discussion #1470 

D'après la réponse ça a été fixé dans la version qui a suivi la 3.2.2
>Bonjour,
Cette anomalie identifiée sur la version 3.2.2 a été corrigée dans la dernière version (beta) publiée sur la page de Release: https://github.com/SocialGouv/archifiltre-docs/releases
(msg de Chloé)


J'ai pas trouvé la mention dans les changelog
@ChloeMoser tu confirmes que c'est fixé ?

**Comment by ChloeMoser** [comment]
Oui, je confirme, c'est bien corrigé.

**Comment by sam-pires** [comment]
Merci !
