### ISSUE TITLE
Le système de tag ("tag"+"no séquentiel") empêche de combiner des fichiers car les colonnes sont différentes

### ISSUE THREAD

**Issue by sam-pires** [SocialGouv/archifiltre-docs#1573]
Bonjour,

Archifiltre ne permet pas l'analyse d'un trop grand répertoire, ni d'un serveur directement à la racine. Qu'à cela ne tienne, j'ai produit mes 300 analyses pour mes 300 sous-répertoires. Afin de faciliter l'analyse des csv/xls que j'avais produit, j'ai utilisé Power Query pour combiner les fichiers de récolement. Cela dit, il y a une erreur en raison des tags. Si je tag en premier le mot "réalisé", par exemple, ça va donner une colonne "tag0: réalisé". Si je le crée en 2e, ça me donne "tag1 : réalisé". Donc, je ne peux pas combiner les fichiers, puisque le nom de la colonne n'est pas le même à cause du préfixe tag+no séquentiel. Mon service de TI avait pensé à faire un script pour renommer les colonnes en lot, mais le problème est que le nombre de colonne est variable selon le nombre de tag que je vais utiliser.

Ce serait vraiment utile si Archifiltre avait un maximum de tag, pour que les fichiers de récolement aient le même nombre de colonnes. Aussi, ça aiderait si le nom de ces colonnes n'était que le nom de tag sans le préfixe "tag"+"no séquentiel". Ou alors, que le préfixe soit toujours le même (ex. : "tag", sans no séquentiel).

Merci!

Alexandre

_Originally posted by @Alexandre-De in https://github.com/SocialGouv/archifiltre-docs/discussions/1437#discussioncomment-3400994_

**Comment by Loracahur010203** [comment]
Bonjour,
Votre demande concernant les "tag" n'est pas conforme au SEDA. Cela mettra en difficulté les utilisateurs voulant exporter des csv vers Resip pour créer un paquet pour l'archivage.
Cordialement

**Comment by sam-pires** [comment]
Bonjour,
Afin de conserver la compatibilité SEDA pour les imports dans ReSIP notamment, nous ne ferons pas évoluer le nom du tag pour le moment.
Je ferme l'issue
