### ISSUE TITLE
Export vers Resip compatibilité du format "date"

### ISSUE THREAD

**Issue by sam-pires** [SocialGouv/archifiltre-docs#1574]
### Discussed in https://github.com/SocialGouv/archifiltre-docs/discussions/1514

<div type='discussions-op-text'>

<sup>Originally posted by **Loracahur** February  8, 2023</sup>
Bonjour,
L'import dans Resip du fichier de métadonnées non modifié se passe bien. Si j'apporte un enrichissement (ex : "description") à ce fichier, le fichier ne peut plus être utilisé à cause du format date "JJ/mm/aaaa". J'ai changé le format de date en "aaaa-mm-jj" (format "Anglais (Royaume Uni)". Resip à accepté de nouveau le csv.
[erreur_date.docx](https://github.com/SocialGouv/archifiltre-docs/files/10686030/erreur_date.docx)
</div>
<img width="962" alt="Capture d’écran 2023-12-20 à 09 46 09" src="https://github.com/SocialGouv/archifiltre-docs/assets/25405887/22377474-b27a-4731-8115-df0a95712351">

**Comment by sam-pires** [comment]
@loracahur je continue ici :

Habituellement ReSIP n'accepte que les dates sous le format Anglais (R-U) ou le format jj/mm/aaaa marche également ?

**Comment by sam-pires** [comment]
@loracahur 
J'ai comparé les formats des dates dans les colonnes des exports avant et après enrichissement.
J'ai 3 colonnes dates:
- `StartDate`	
- `EndDate`	
- `TransactedDate`
Dans les 2 cas les dates sont au format aaaa-mm-jj

Dans quelle colonne avez-vous le format jj/mm/aaaa ?

**Comment by Loracahur** [comment]
Bonjour,
Lors de l’export du csv « Resip » le format de date et respecté. Seulement quand on modifie le csv ex : colonne « tag », le format de date change dans le csv. Pour finir, cet erreur n’est pas dû à Archifitre mais à Excel. Les préconisations et la mise en garde étaient pour les personnes qui importent des paquets d’archives dans Vitam.

Bien cordialement,

***@***.***

Carol RUHA
Assistant archiviste
Direction Relation à l'Usager et Services Internes
Ville de Cergy
Tél : 01 34 33 44 65
Hôtel de ville - 3, place Olympe de Gouges
BP 48 000 Cergy – 95 801 Cergy-Pontoise cedex
[logos sociaux]  villedecergy   [instagram]  JeunesACergy<http://www.instagram.com/jeunesacergy/> - www.cergy.fr<http://www.cergy.fr/>












De : Samuel Pirès ***@***.***>
Envoyé : mardi 19 décembre 2023 19:15
À : SocialGouv/archifiltre-docs ***@***.***>
Cc : RUHA, Carol ***@***.***>; Mention ***@***.***>
Objet : Re: [SocialGouv/archifiltre-docs] Export vers Resip compatibilité du format "date" (Issue #1574)


@Loracahur<https://eu-west-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL0xvcmFjYWh1cg==&i=NjAyYmI0OGIxZGJjZjQyNWMyMTA1MDUz&t=K29ScVQ4ajNxWUZ4T0FGM2ZpN0RUREpTMnF4OUFsVERyekJhK0VtSTd2ST0=&h=53b22953e7a64dc59c84e21c0e331bf7&s=AVNPUEhUT0NFTkNSWVBUSVa7Z56Wl0HUa2InR2X4iZf_VhFb887oT0fj-Wj-_R9rEA>
J'ai comparé les formats des dates dans les colonnes des exports avant et après enrichissement.
J'ai 3 colonnes dates:

  *   StartDate
  *   EndDate
  *   TransactedDate
Dans les 2 cas les dates sont au format aaaa-mm-jj

Dans quelle colonne avez-vous le format jj/mm/aaaa ?

**Comment by sam-pires** [comment]
Je comprends mieux
Merci @loracahur :) 

Je vais voir pour mettre cette info/reco dans un guide/aide si d'autres personnes rencontrent le problème.
