### ISSUE TITLE
Proposer un export "Bordereau d'élimination"

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1584]
### EPIC

SocialGouv/archifiltre-private#

### AFTER

#

### Contexte

Quand les utilisateurs taguent des éléments à éliminer, proposer un export comportant d'office tous les éléments qui ont été tagués

### Solution

Créer un nouvel export CSV comportant les éléments tagués "A éliminer"
Ajouter cet export dans la liste des exports possibles

### Les tests e2e doivent-ils passer ?

- [ ] e2e

**Comment by sam-pires** [comment]
Hello
Je ferme cette issue car il s'agit d'une feature qui demande de la conception, je l'ai dupliquée dans Notion
