### ISSUE TITLE
Dans l'onglet redondances, pouvoir afficher également les dossiers redondants

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1586]
### EPIC

SocialGouv/archifiltre-private#

### AFTER

#

### Définition du(des) problème(s)

Actuellement, Archifiltre n'affiche que les documents présents plusieurs fois, nous aurions besoin de pouvoir afficher les répertoires en doublons également

### Les tests e2e doivent-ils passer ?

- [ ] e2e

**Comment by sam-pires** [comment]
Je ferme car il s'agit d'une feature et qu'elle est déjà dans le backlog et featurebase
