### ISSUE TITLE
Statistiques: Pouvoir afficher les pays d'où nos utilisateurs se connectent

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1587]
### EPIC

SocialGouv/archifiltre-private#

### AFTER

#

### Contexte

Dans PostHog, nous n'avons pas la possibilité d'avoir une carte de la localisation (par pays) de nos utilisateurs

### Solution

Faire remonter les pays de ceux qui téléchargent Archifiltre et de ceux qui déposent des arborescences à analyser

### Les tests e2e doivent-ils passer ?

- [ ] e2e

**Comment by sam-pires** [comment]
J'avais commencé à regarder avec Mehdi, ça passe par un plugin dans PostHog qui doit faire remonter l'IP et la localisation sous plusieurs format possible (GeoIP il me semble. Il est activé mais ne remonte rien.


Si besoin de plus creuser sur Posthog on peut déjà récupérer les données qui viennent de Matomo (ça ne prend en compte que les versions avant la 4.0.0 mais c'est déjà ça)

**Comment by sam-pires** [comment]
https://docs.posthog.archifiltre.fr/project/plugins

**Comment by sam-pires** [comment]
Je ferme car ça ne porte pas sur Docs
