### ISSUE TITLE
Vérifier la mise à jour des mentions légales du site

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1589]
### EPIC

SocialGouv/archifiltre-private#

### AFTER

#

### Solution

Texte doit être:
texte à mettre

Mentions légales – Archifiltre

Éditeur de la plateforme

Direction du Numérique des ministères sociaux

Ministère des solidarités et de la santé

39-43 Quai André Citroën

75739 Paris Cedex 15

Directrice de la publication

Madame Anne JEANJEAN, Directrice du Numérique des ministères sociaux

Hébergement de la plateforme

Microsoft Azure

37-39 Quai du Président Roosevelt

92130 Issy les Moulineaux

Accessibilité

La conformité aux normes d’accessibilité numérique est un objectif ultérieur mais nous tâchons de rendre cette plateforme accessible à toutes et tous.

Signaler un dysfonctionnement

Si vous rencontrez un défaut d’accessibilité vous empêchant d’accéder à un contenu ou une fonctionnalité de la plateforme, merci de nous en faire part.

Si vous n’obtenez pas de réponse rapide de notre part, vous êtes en droit de faire parvenir vos doléances ou une demande de saisine au Défenseur des droits.

### Les tests e2e doivent-ils passer ?

- [ ] e2e

**Comment by sam-pires** [comment]
Je ferme car ne porte pas sur Docs
