### ISSUE TITLE
[Audit Archifiltre docs] Erreur pourcentage doublons

### ISSUE THREAD

**Issue by GParisisPLD** [SocialGouv/archifiltre-docs#1602]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Bonjour,

J'ai remarqué que les pourcentages de doublons des audits ne sont pas bons. En effet, les pourcentages donnés ne correspondent pas aux chiffres bruts donnés. Par exemple :
![image](https://github.com/SocialGouv/archifiltre-docs/assets/157126004/10877a8e-167c-46b6-aa49-653859ce478e)
![Capture](https://github.com/SocialGouv/archifiltre-docs/assets/157126004/e736f3fc-fa34-4482-9830-727bad492c45)

En comparant avec un audit fait avec la version précédente (3.2.2), les chiffres bruts sont les mêmes mais les pourcentages. Et en faisant le calcul manuellement, les pourcentages donnés ne sont pas les mêmes que ceux de l'audit.

Il me semble que le problème vient du calcul de l'audit qui ne multiplie pas par 100 après avoir divisé le nombre de doublons par le nombre total.

Cordialement,
Guillaume Parisis

### Version de l'application

4.x

**Comment by sam-pires** [comment]
Bonjour @GParisisPLD 
Merci pour le ticket, on va regarder

**Comment by sam-pires** [comment]
Résolu dans la v4.1 ✅
