### ISSUE TITLE
Passage de page dans l'onglet Redondances

### ISSUE THREAD

**Issue by BenjaminPrds** [SocialGouv/archifiltre-docs#1623]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Bonjour,
Dans l'onglet Redondances, dans la liste des résultats, les boutons pour se rendre à la page suivante ou à la dernière ne répondent pas.

### Étapes pour reproduire

Charger un projet
A la fin de l'analyse, se rendre dans l'onglet Redondances
Cliquer sur page suivante ou dernière page en bas à droite

### Liste des caractéristiques de votre machine

Windows 10 Pro version 22H2
Proc 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz 
RAM 8,00 Go
Version Docs 4.1.0 stable

### Version de l'application

4.x

**Comment by sam-pires** [comment]
Bug résolu, sera disponible dans la prochaine version (4.1.1 ou 4.2)

**Comment by sam-pires** [comment]
Bonjour,

Le bug a été corrigé dans notre dernière release v.4.1.2 🛠️
Vous pouvez la télécharger sur notre [site](https://archifiltre.fr/) ou directement sur [Github](https://github.com/SocialGouv/archifiltre-docs/releases) si vous cherchez une version spécifique.


Merci pour votre aide 😃
