### ISSUE TITLE
Fichiers exportés introuvables

### ISSUE THREAD

**Issue by ArchivistIn** [SocialGouv/archifiltre-docs#1626]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

J'utilise votre nouvelle version d'archifiltre sur votre nouvelle version v4.1.0 (stable) pour tester plusieurs fonctionnalités "enhancements" (nouveau nommage, commentaires, plusieurs tags, etc) afin de les montrer à mon équipe informatique. J'ai choisi un très petit dossier (23 documents) sur lequel j'ai des accès read-only. Je souhaite exporter des rapports, si possible tous les types de rapports, mais au moins l'excel, le CSV tree et le deletion script. Les exports sont "created", "succeeded" ou "exported", mais le téléchargement n'arrive pas à 100 pour 100 et les fichiers ne semblent pas être accessibles.

### Captures d'écran (si possible)

![image](https://github.com/SocialGouv/archifiltre-docs/assets/164012379/b6fc4673-33cd-4209-ab1f-9dfa5335bec3)
![image](https://github.com/SocialGouv/archifiltre-docs/assets/164012379/62afed55-cc79-4ffa-844d-620b121effe2)

### Version de l'application

None

**Comment by sam-pires** [comment]
Bonjour @ArchivistIn 
Merci pour le retour et désolé pour le désagrément.

Les exports ne sont pas du tout générés ? ou ils le sont mais vous ne pouvez pas les ouvrir ?
Nous avons remarqué qu'il se peut que les barres de progression des exports n'atteignent pas 100% mais que les fichiers soient quand même bien générés.

**Comment by ArchivistIn** [comment]
Bonjour !
Les exports ne sont pas du tout générés (je n'ai pas la fenêtre verte cliquable habituelle dans Archifiltre lorsque les fichiers sont prêts, je ne les trouve pas non plus dans mes downloads, ni nulle part ailleurs sur le pc)
Merci pour votre aide : )

**Comment by sam-pires** [comment]
Related to #1628

**Comment by sam-pires** [comment]
Bonjour,

Le bug a été corrigé dans notre dernière release v.4.1.2 🛠️
Vous pouvez la télécharger sur notre [site](https://archifiltre.fr/) ou directement sur [Github](https://github.com/SocialGouv/archifiltre-docs/releases) si vous cherchez une version spécifique.


Merci pour votre aide 😃
