### ISSUE TITLE
Fichier Tree CSV analyse une virgule comme un niveau

### ISSUE THREAD

**Issue by ArchivistIn** [SocialGouv/archifiltre-docs#1627]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Bonjour,
En exportant un fichier tree CSV avec la version Archifiltre 4.1.10 (stable), il y a un bug sur les niveaux de documents à cause de virgules dans le nommage qui sont mal interprétées. Le dossier contient 18 documents et a deux niveaux (le dossier ; ses fichiers).
En revanche :
Dans le fichier tree CSV, le nom du dossier source et noms des documents qu'il contient sont en colonne 1, comme s'ils étaient au même niveau.
Le deuxième niveau (colonne 2) contient le partie après la virgule du nommage des 2 documents contenant une virgule dans leur nommage, ce sont des données erronées

### Captures d'écran (si possible)

![image](https://github.com/SocialGouv/archifiltre-docs/assets/164012379/c9b7b726-9d67-44fa-9956-4624b955b8a6)

### Version de l'application

None

**Comment by sam-pires** [comment]
Bonjour @ArchivistIn 
J'ai tout essayé et je n'arrive pas à reproduire.
J'ai utilisé la virgule et le point virgule, avec espace avant, après, les deux... et je ne reproduis pas l'erreur. l'arboresence dans l'export CSV hiérarchisé s'affiche bien.

Je pense que le problème vient plutôt de comment votre logiciel de tableur lit le CSV, avez-vous défini des options sur la lecture des virgules et points virgules.

Par exemple, voici ce qui se passe si j'essaye d'ouvrir le csv avec GoogleSheet (je n'avais que ça sous la main):
<img width="894" alt="Capture d’écran 2024-04-03 à 06 47 10" src="https://github.com/SocialGouv/archifiltre-docs/assets/25405887/2137e1cc-07f4-492a-b77d-f88f49e6b5f0">
je peux définir le comportement vis à vis de certains caractères.


Pouvez-vous vérifier de ce côté là svp ?
