### ISSUE TITLE
Fichier avec empreinte non généré et non exporté

### ISSUE THREAD

**Issue by ChrisGitNew** [SocialGouv/archifiltre-docs#1628]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Avec la version 4.1 d'archifiltre, l'analyse d'un répertoire est faite à 100% (génération des empreintes). Cependant seul le fichier d'Audit, le fichier d'arboresence sont générés. Le fichier csv avec empreintes n'est pas généré à 100% lorsque je lance l'export. 

### Étapes pour reproduire

Il suffit de lancer l'analyse et d'essayer d'importer les fichiers générés par archifiltre

### Comportement attendu

Obtenir le fichier csv avec empreintes

### Version de l'application

4.x

### Informations complémentaires

Version 4.1 mise à jour sur le poste utiliséé

**Comment by Bernard-VAL** [comment]
Bonjour,

J'ai le même comportement avec la V 4.1.
J'ai donc repris la version précédente pour pouvoir générer les Csv avec empreintes.

Bernard Leulliette

**Comment by ChrisGitNew** [comment]
Bonjour,
le problème c'est que je ne réussis pas à réinstaller la version 4.0. Il me
met automatiquement la version 4.1!
Comment avez-vous fait?

*Christelle OLIVA-WEILL *



*Cheffe de projets SI*

Mail : ***@***.***

Tel: 06 67 41 23 83

www.rejoue.asso.fr



Le lun. 25 mars 2024 à 14:48, Bernard-VAL ***@***.***> a
écrit :

**Comment by Bernard-VAL** [comment]
Je suis reparti avec la version v 4.00-beta11 que j'avais gardé sur un PC

Bernard Leulliette

**Comment by sam-pires** [comment]
@ChrisGitNew 
Merci pour l'info, on regarde le problème.

Pour repasser sur la 4.0, vous pouvez la récupérer sur Github directement, à cet endroit : https://github.com/SocialGouv/archifiltre-docs/releases

Il peut être utile de supprimer la 4.1 de votre poste avant de réinstaller une autre

**Comment by ChrisGitNew** [comment]
Bonjour,
Je vais retenter la manipulation mais c'est bien ce que j'ai essayé de
faire. Est-ce qu'il y a plusieurs fichiers à supprimer pour désinstaller la
version 4.1?

Encore merci de votre appui.
Christelle


*Christelle OLIVA-WEILL *

*Cheffe de projets SI*

Mail : ***@***.***

Tel: 06 67 41 23 83

www.rejoue.asso.fr



Le lun. 25 mars 2024 à 18:21, Samuel Pirès ***@***.***> a
écrit :

**Comment by ChrisGitNew** [comment]
Bonjour monsieur Pirès,
Excusez-moi de vous déranger encore à ce sujet, mais même à partir de ce
lien (j'y étais déjà allée) je n'arrive pas à savoir où est le programme à
télécharger.

Est-ce que vous auriez une indication plus précise à me donner sur le lien
de téléchargement de la version 4.0 svp?

D'avance merci.

Bonne journée et belle fin de semaine,

Christelle

*Christelle OLIVA-WEILL *

*Cheffe de projets SI*

Mail : ***@***.***

Tel: 06 67 41 23 83

www.rejoue.asso.fr



Le lun. 25 mars 2024 à 18:21, Samuel Pirès ***@***.***> a
écrit :

**Comment by sam-pires** [comment]
> Bonjour monsieur Pirès, Excusez-moi de vous déranger encore à ce sujet, mais même à partir de ce lien (j'y étais déjà allée) je n'arrive pas à savoir où est le programme à télécharger. Est-ce que vous auriez une indication plus précise à me donner sur le lien de téléchargement de la version 4.0 svp? D'avance merci. Bonne journée et belle fin de semaine, Christelle *Christelle OLIVA-WEILL * *Cheffe de projets SI* Mail : ***@***.*** Tel: 06 67 41 23 83 [www.rejoue.asso.fr](http://www.rejoue.asso.fr) Le lun. 25 mars 2024 à 18:21, Samuel Pirès ***@***.***> a écrit :

Bonjour @ChrisGitNew 
Vous trouverez la dernière version 4.0.0 (next 14) ici : https://github.com/SocialGouv/archifiltre-docs/releases/tag/v4.0.0-next.14

En base de pages se trouvent la liste des assets.
Si vous êtes sur Mac, téléchargez l'asset : [archifiltre-docs-mac-x64.dmg](https://github.com/SocialGouv/archifiltre-docs/releases/download/v4.0.0-next.14/archifiltre-docs-mac-x64.dmg)
Si vous êtes sur Windows, téléchargez l'asset : [archifiltre-docs-win-x64-setup.exe](https://github.com/SocialGouv/archifiltre-docs/releases/download/v4.0.0-next.14/archifiltre-docs-win-x64-setup.exe)

**Comment by sam-pires** [comment]
Bonjour,

Le bug a été corrigé dans notre dernière release v.4.1.2 🛠️
Vous pouvez la télécharger sur notre [site](https://archifiltre.fr/) ou directement sur [Github](https://github.com/SocialGouv/archifiltre-docs/releases) si vous cherchez une version spécifique.


Merci pour votre aide 😃

**Comment by sam-pires** [comment]
Je réouvre le problème exacte n'est pas résolu, mais reproduit et nous travaillons dessus


related to #1518

**Comment by sam-pires** [comment]
Le problème exacte n'est pas résolu, mais reproduit et nous travaillons dessus


Related to #1518

**Comment by sam-pires** [comment]
Bonjour @ChrisGitNew 
Nous avons résolu ce bug dans la version 4.2.0 qui vient de sortir !
Vous pouvez la télécharger sur notre site https://archifiltre.fabrique.social.gouv.fr/telechargement
