### ISSUE TITLE
La documentation ne s'ouvre pas

### ISSUE THREAD

**Issue by Chlara** [SocialGouv/archifiltre-docs#1631]
### User Story

SocialGouv/archifiltre-docs#

### Description du bug

Je ne peux pas ouvrir la documentation, ni la page d'accueil ou le wiki. La langue que j'ai choisie n'a aucune importance (FR, EN, DE).

### Étapes pour reproduire

1. Cliquer sur Documentation / Site web / Wiki.
2. Pas de réaction.

### Comportement attendu

1. Cliquer sur Documentation / Site web / Wiki.
2. La documentation devrait s'ouvrir. 

### Captures d'écran (si possible)

![Screenshot 2024-04-03 093201](https://github.com/SocialGouv/archifiltre-docs/assets/1552939/32a1a11b-eb0c-4764-a594-b4fd942e9bc3)

### Liste des caractéristiques de votre machine

Windows 11

J'ai essayé les deux installations suivantes (4.1.0) :

- archifiltre-docs-win-x64-setup.exe
- archifiltre-docs-win-x64-portable.exe

### Version de l'application

4.x

**Comment by sam-pires** [comment]
Bonjour,

Le bug a été corrigé dans notre dernière release v.4.1.1 🛠️
Vous pouvez la télécharger sur notre [site](https://archifiltre.fr/) ou directement sur [Github](https://github.com/SocialGouv/archifiltre-docs/releases) si vous cherchez une version spécifique.


Merci pour votre aide 😃
