### ISSUE TITLE
Création de l'export Excel bloqué 

### ISSUE THREAD

**Issue by CamLka** [SocialGouv/archifiltre-docs#1659]
### Description du bug

La création de l'export Excel reste bloquée à 99% malgré plusieurs tentatives et redémarrages successifs. Lorsque de la création du fichier se bloque, plus aucune commande de Docs ne réagit. Il faut fermer et redémarrer le logiciel pour pouvoir l'utiliser à nouveau.

### Étapes pour reproduire

Sur l'onglet général, cliquer sur "exporter"
Dans la fenêtre pop-up, sélectionner "Excel"
Cliquer sur "Exporter"
La création du fichier excel démarre mais se bloque à 99% et Docs ne répond plus.

### Comportement attendu

Création complète et enregistrement du fichier excel.

### Captures d'écran (si possible)

![image](https://github.com/user-attachments/assets/80541b73-7049-4817-bbf8-eed38e6e2582)

### Liste des caractéristiques de votre machine

Windows 10 Enterprise
RAM 32.0 GB (31.7 GB usable)

### Version de l'application

4.2.0

### Informations complémentaires

Le problème se présente depuis le 24/09/2024. Il se présentait sur la version précédente utilisée jusqu'à aujourd'hui.

**Comment by sam-pires** [comment]
Bonjour @CamLka 
Merci de nous avoir fait remonter le problème.

On va regarder ça dès cette semaine.

**Comment by sam-pires** [comment]
Bonjour @CamLka 

Guillaume notre développeur a apporté une correction au bug.
Le correctif est accessible dans la **v4.2.1-beta.1**, nous sommes en train de la tester avant de la sortir officiellement.

Pouvez-vous tester la version beta avec votre fichier pour voir si le problème est bien résolu svp ?
Pour la télécharger allez sur [cette page](https://github.com/SocialGouv/archifiltre-docs/releases/tag/v4.2.1-beta.1), et dans la partie "Asset", toutes les versions sont listées 
<img width="632" alt="Capture d’écran 2024-10-06 à 16 08 16" src="https://github.com/user-attachments/assets/2ed3219f-6b02-4afa-81d5-ff9061b5964e">

Pour Windows vous pouvez prendre ces 2 versions :
- [archifiltre-docs-win-setup.exe](https://github.com/SocialGouv/archifiltre-docs/releases/download/v4.2.1-beta.1/archifiltre-docs-win-setup.exe)
- si la première ne fonctionne pas, essayez celle-ci [archifiltre-docs-win-portable.exe](https://github.com/SocialGouv/archifiltre-docs/releases/download/v4.2.1-beta.1/archifiltre-docs-win-portable.exe)


Tenez nous au courant 🙂

**Comment by sam-pires** [comment]
Résolu en v4.2.1
